# Generated by Django 3.1.6 on 2021-02-22 08:59

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200713_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='box_art',
            field=models.FileField(upload_to=games.models.games_box_art_path),
        ),
    ]
